import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./component/Navbar";
import Home from "./component/Home";
import Footer from "./component/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Neutrixinc",
  description: "Generated by Neutrixinc",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className=' shadow-sm'>
          <Navbar />
        </div>
        <Home />

        {children}

        <Footer />
      </body>
    </html>
  );
}
