import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./component/Navbar";
import Home from "./component/Home";
import Footer from "./component/Footer";
import Cards from "./component/Cards";
import Report from "./component/Report";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Neutrixinc",
  description: "Generated by Neutrixinc",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className=' shadow-sm'>
          <Navbar />
        </div>
        {children}
        <div className=" container mx-auto">
          <Cards />
          <Report />
        </div>
        <Footer />
      </body>
    </html>
  );
}
